# Generated by Django 5.1.7 on 2025-04-14 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('Userid', models.IntegerField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=30)),
                ('Email_Id', models.CharField(max_length=30)),
                ('Phone_number', models.IntegerField()),
                ('Moviename', models.CharField(max_length=20)),
                ('Show_date', models.DateField()),
                ('Show_time', models.TimeField()),
                ('No_of_seats', models.IntegerField()),
            ],
        ),
    ]
